spring:
  application:
    name: mytrello
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSql
    username: test
    password: test
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 50
  flyway:
    locations:
      - classpath:migrations
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  error:
    include-message: always
    include-exception: true

application:
  pagination-feature: true
