ALTER TABLE users RENAME COLUMN firstName TO first_name;
ALTER TABLE users RENAME COLUMN lastName TO last_name;
ALTER TABLE users RENAME COLUMN timeZone TO time_zone;
ALTER TABLE users ALTER COLUMN first_name TYPE VARCHAR(20);
ALTER TABLE users ALTER COLUMN last_name TYPE VARCHAR(30);
ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(30);
ALTER TABLE members RENAME TO member;
ALTER TABLE member RENAME COLUMN roles TO "role";
ALTER TABLE member ALTER COLUMN "role" TYPE VARCHAR(10);
ALTER TABLE workspaces RENAME TO workspace;
ALTER TABLE workspace RENAME COLUMN createdBy TO created_by;
ALTER TABLE workspace RENAME COLUMN updatedBy TO updated_by;
ALTER TABLE workspace RENAME COLUMN createdDate TO created_date;
ALTER TABLE workspace RENAME COLUMN updatedDate TO updated_date;
ALTER TABLE workspace ALTER COLUMN "name" TYPE VARCHAR(40);
ALTER TABLE workspace ALTER COLUMN description TYPE VARCHAR(200);
ALTER TABLE workspace ALTER COLUMN visibility TYPE VARCHAR(40);
ALTER TABLE workspace ALTER COLUMN created_by TYPE VARCHAR(40);
ALTER TABLE workspace ALTER COLUMN updated_by TYPE VARCHAR(40);
ALTER TABLE boards RENAME TO board;
ALTER TABLE board ALTER COLUMN "name" TYPE VARCHAR(40);
ALTER TABLE board ALTER COLUMN description TYPE VARCHAR(200);
ALTER TABLE board ALTER COLUMN visibility TYPE VARCHAR(20);
ALTER TABLE board RENAME COLUMN createdBy TO created_by;
ALTER TABLE board RENAME COLUMN updatedBy TO updated_by;
ALTER TABLE board RENAME COLUMN createdDate TO created_date;
ALTER TABLE board RENAME COLUMN updatedDate TO updated_date;
ALTER TABLE board ALTER COLUMN created_by TYPE VARCHAR(40);
ALTER TABLE board ALTER COLUMN updated_by TYPE VARCHAR(40);
ALTER TABLE colors RENAME TO color;
ALTER TABLE labels RENAME TO label;
ALTER TABLE label ALTER COLUMN "name" TYPE VARCHAR(20);
ALTER TABLE cardlists RENAME TO cardlist;
ALTER TABLE cardlist ALTER COLUMN "name" TYPE VARCHAR(40);
ALTER TABLE cardlist RENAME COLUMN createdBy TO created_by;
ALTER TABLE cardlist RENAME COLUMN updatedBy TO updated_by;
ALTER TABLE cardlist RENAME COLUMN createdDate TO created_date;
ALTER TABLE cardlist RENAME COLUMN updatedDate TO updated_date;
ALTER TABLE cardlist ALTER COLUMN created_by TYPE VARCHAR(40);
ALTER TABLE cardlist ALTER COLUMN updated_by TYPE VARCHAR(40);
ALTER TABLE reminders RENAME TO reminder;
ALTER TABLE reminder RENAME COLUMN createdBy TO created_by;
ALTER TABLE reminder RENAME COLUMN updatedBy TO updated_by;
ALTER TABLE reminder RENAME COLUMN createdDate TO created_date;
ALTER TABLE reminder RENAME COLUMN updatedDate TO updated_date;
ALTER TABLE reminder RENAME COLUMN start_data TO start_at;
ALTER TABLE reminder RENAME COLUMN end_data TO end_at;
ALTER TABLE reminder RENAME COLUMN remindOn TO remind_on;
ALTER TABLE reminder RENAME COLUMN acttive TO active;
ALTER TABLE reminder ALTER COLUMN created_by TYPE VARCHAR(40);
ALTER TABLE reminder ALTER COLUMN updated_by TYPE VARCHAR(40);
ALTER TABLE cards RENAME TO card;
ALTER TABLE card ALTER COLUMN "name" TYPE VARCHAR(40);
ALTER TABLE card ALTER COLUMN description TYPE VARCHAR(200);
ALTER TABLE card RENAME COLUMN createdBy TO created_by;
ALTER TABLE card RENAME COLUMN updatedBy TO updated_by;
ALTER TABLE card RENAME COLUMN createdDate TO created_date;
ALTER TABLE card RENAME COLUMN updatedDate TO updated_date;
ALTER TABLE card ALTER COLUMN created_by TYPE VARCHAR(40);
ALTER TABLE card ALTER COLUMN updated_by TYPE VARCHAR(40);
ALTER TABLE comments RENAME TO comment;
ALTER TABLE comment
    ADD COLUMN text varchar(140);
ALTER TABLE comment RENAME COLUMN createdBy TO created_by;
ALTER TABLE comment RENAME COLUMN updatedBy TO updated_by;
ALTER TABLE comment RENAME COLUMN createdDate TO created_date;
ALTER TABLE comment RENAME COLUMN updatedDate TO updated_date;
ALTER TABLE comment ALTER COLUMN created_by TYPE VARCHAR(40);
ALTER TABLE comment ALTER COLUMN updated_by TYPE VARCHAR(40);
ALTER TABLE attachments RENAME TO attachment;
ALTER TABLE attachment ALTER COLUMN "name" TYPE VARCHAR(40);
ALTER TABLE attachment RENAME COLUMN createdBy TO created_by;
ALTER TABLE attachment RENAME COLUMN updatedBy TO updated_by;
ALTER TABLE attachment RENAME COLUMN createdDate TO created_date;
ALTER TABLE attachment RENAME COLUMN updatedDate TO updated_date;
ALTER TABLE attachment ALTER COLUMN created_by TYPE VARCHAR(40);
ALTER TABLE attachment ALTER COLUMN updated_by TYPE VARCHAR(40);
ALTER TABLE checkableitems RENAME TO check_able_item;
ALTER TABLE check_able_item ALTER COLUMN "name" TYPE VARCHAR(40);
ALTER TABLE check_able_item RENAME COLUMN checkedSwitcher TO checked;
ALTER TABLE check_able_item DROP COLUMN createdBy RESTRICT;
ALTER TABLE check_able_item DROP COLUMN updatedBy RESTRICT;
ALTER TABLE check_able_item DROP COLUMN createdDate RESTRICT;
ALTER TABLE check_able_item DROP COLUMN updatedDate RESTRICT;
ALTER TABLE checklists RENAME TO checklist;
ALTER TABLE checklist ALTER COLUMN "name" TYPE VARCHAR(40);
ALTER TABLE checklist RENAME COLUMN createdBy TO created_by;
ALTER TABLE checklist RENAME COLUMN updatedBy TO updated_by;
ALTER TABLE checklist RENAME COLUMN createdDate TO created_date;
ALTER TABLE checklist RENAME COLUMN updatedDate TO updated_date;
ALTER TABLE checklist ALTER COLUMN created_by TYPE VARCHAR(40);
ALTER TABLE checklist ALTER COLUMN updated_by TYPE VARCHAR(40);




